<?xml version="1.0" encoding="utf-8" ?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:tns="http://www.opengis.net/wps/1.0.0" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.opengis.net/wps/1.0.0">
				<types  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
					<xsd:schema targetNamespace="http://whateverNS">
						<xsd:import namespace="http://www.opengis.net/wps/1.0.0" schemaLocation="http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd"/>
					</xsd:schema>
				</types>
				<message  name="InputMessage">
					<part element="wps:Execute" name="InPart"/>
				</message>
				<message  name="OutputMessage">
					<part element="wps:ExecuteResponse" name="OutPart"/>
				</message>
				<portType  name="ExecutePortType">
					<operation name="Execute">
						<input message="tns:InputMessage"/>
						<output message="tns:OutputMessage"/>
					</operation>
				</portType>
				<binding  name="HTTPPOSTBinding" type="tns:ExecutePortType">
					<http:binding verb="POST"/>
					<operation name="Execute">
						<http:operation location=""/>
						<input>
							<mime:content part="InPart" type="text/xml"/>
						</input>
						<output>
							<mime:content part="OutPart" type="text/xml"/>
						</output>
					</operation>
				</binding>
				<service  name="AustalWPS">
					<port binding="tns:HTTPPOSTBinding" name="AustalWPSPort">
						<http:address location="http://localhost:8080/wps2/WebProcessingService"/>
					</port>
				</service>
			</definitions>